language: perl
before_install: perlbrew -f install-cpanm
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
env:
  - STF_QUEUE_TYPE=Schwartz
  - STF_QUEUE_TYPE=Resque
  - STF_QUEUE_TYPE=Redis
